### ISSUE TITLE
Problems after first time installation.

### ISSUE THREAD

**Issue by DreamyPhobic** [opendatakit/share#109]
#### Problem Description
There are some problems at initial setup of the app. With initial setup, I mean there is no data in  collect as well as in share. 
1. It will not show the Empty view TextView with text "No Blank forms available". 
2. On clicking send button when there is no forms available, will result in crash. As reported in #100.

These two problems are arising, because at first time use, the cursor will be null.

**Cause of 1st problem** : the method ```setEmptyViewVisibility()```is skipped all the time as it is only called when cursor is not equal to null. (Same behaviour at FilledFormsFragment and BlankFormsFragment)

![screenshot_2019-02-20-23-48-23-79 2](https://user-images.githubusercontent.com/33078171/53114912-ef5a7880-356a-11e9-8a56-f9b6a6ea9558.jpg)

**Cause of 2nd problem** : in onLoadFinished() method in FilledFormsFragment and BlankFormsFragment, cursor is directly accessed without null check.

> java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
        at org.odk.share.fragments.FilledFormsFragment.onLoadFinished(FilledFormsFragment.java:93)
        at org.odk.share.fragments.FilledFormsFragment.onLoadFinished(FilledFormsFragment.java:39)

#### Steps To Reproduce:

1. Delete all the data of collect and share.
2. Reinstall both the apps in your device.
3. Don't import any blank forms in collect.
4. Launch the share app, you will find all these problems.

#### Other Informations
Disabling the send button as proposed in #102, when there are no forms, can solve 2nd problem but it will not ensure the data consistency as cursor is accessed without null check.

**Comment by DreamyPhobic** [comment]
I think few changes in ```setEmptyViewVisibility()``` and null check for cursor can resolve both issues.
I like to work on it myself.
