### ISSUE TITLE
If portable hotspot configuration fails, no feedback is given

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#51]
On two of the devices I've tried (Galaxy Tab A and Alcatel One Touch 5020D, details at https://github.com/opendatakit/collect#contributing-testing), when I tap "Send" and select filled forms, I go straight to a screen that shows "Waiting for connection to accept". What does this state means? It looks like it's not possible to set up a hostpot on those devices? I don't get promtped to enable from the settings.

On the Moto G4 I do get prompted to enable the hotspot from settings. Then I see the QR code and port number information.

**Comment by lognaturel** [comment]
Interesting, I just noticed that on the One Touch, I get a notification that the hotspot has been started. In settings, it looks correctly configured. But I still just see "Waiting for connection to accept"

**Comment by lakshyagupta21** [comment]
@lognaturel There were some issues when we configure hotspot for different versions so we tried to apply some tricks to make it work.
Devices with version 
1. < 7 - It gets configured directly from the third app.
2. >= 7 and < 8 - It can be configured from the app but if we enable it from the third party app then other devices won't be able to connect to it, so we navigated a user to `portable hotspot settings` so that it can be enabled by a user manually.
3. >= 8 - For these devices, now there is a public API available which allows third-party apps to enable/disable the Hotspot, but there is a limitation to it, that the apps can't change hotspot name, password, etc and if hotspot is enabled then the devices connected to it won't be able to use its data connection to connect to the internet.

**Comment by lakshyagupta21** [comment]
If you're navigated to a screen showing `Waiting for connection to accept` it means that everything worked perfectly (Configuring and enabling of hotspot) and now it is waiting for other devices to connect to it. Once other device gets connected to it, it starts sending the files.

**Comment by lognaturel** [comment]
If things are working, it should show the QR code and the port, right? When the "Waiting for connection to accept" screen is shown, no other device can find the hotspot and there's no way to connect via QR code.

**Comment by lognaturel** [comment]
To summarize some new insights from Slack:

- Galaxy Tab A, Android 5.1.1: it seems I consistently get 
```
07-19 06:44:23.089 12413-12413/org.odk.share E/WifiHotspotHelper: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at org.odk.share.controller.WifiHotspotHelper.toggleHotspot(WifiHotspotHelper.java:139)
        at org.odk.share.controller.WifiHotspotHelper.enableHotspot(WifiHotspotHelper.java:129)
        at org.odk.share.activities.SendActivity.initiateHotspot(SendActivity.java:146)
        at org.odk.share.activities.SendActivity.startHotspot(SendActivity.java:130)
        at org.odk.share.activities.SendActivity.onCreate(SendActivity.java:105)
        at android.app.Activity.performCreate(Activity.java:6609)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3104)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
        at android.app.ActivityThread.access$1000(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6939)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: java.lang.SecurityException: ConnectivityService: Neither user 10229 nor current process has android.permission.CHANGE_NETWORK_STATE.
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.net.wifi.IWifiManager$Stub$Proxy.setWifiApEnabled(IWifiManager.java:1673)
        at android.net.wifi.WifiManager.setWifiApEnabled(WifiManager.java:2001)
```

- One Touch, Android 4.1.1:
No exception. The hotspot is set up and other devices do see it but then they prompt for a port number but the sending device doesn't show a port number.

**Comment by lognaturel** [comment]
"Waiting for connection to accept" is the default text from the layout. It should probably be more descriptive and state that something went wrong. If things went right, the QR code and port number should be displayed.

**Comment by lognaturel** [comment]
From discussion on Slack: I set a breakpoint at `SendActivity.addUploadEventSubscription` and `SenderService.startUploading` and found that on the Android 4.1.1 device, the queued status event is sent by `startUploading` before the event subscription is done.

**Comment by lognaturel** [comment]
This is probably still a possible state to get in so it would be good for it to say something to help the user along. It could be as simple as "If you're not seeing a QR code here, something went wrong configuring the wifi hotspot"

https://www.smashingmagazine.com/2016/09/how-to-design-error-states-for-mobile-apps/ has some good reading on error states.

**Comment by lognaturel** [comment]
There seems to also be a case where the hotspot configuration fails but a QR code is still shown. That's now what happens for me on the OneTouch Android 4.1.1.
