### ISSUE TITLE
Receiver hangs on "Connecting to wifi"

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#57]
Continuing from https://github.com/opendatakit/share/pull/54#issuecomment-406388616.  

I can reproduce this consistently with the Alcatel One Touch / Android 4.1.1 device receiving. It also seems to happen sporadically on other devices after updating versions.

The devices hang on the "Connecting to wifi" dialog and there is no way to exit other than killing the app. The back button is disabled. Before that it flashes a "already connected" toast.

I'm not certain this is related but on the One Touch, after a while I got:

```
07-19 21:48:28.886 13902-13902/org.odk.share E/WifiActivity: java.lang.IllegalArgumentException: Receiver not registered: org.odk.share.activities.WifiActivity$8@417e6710
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1214)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:378)
        at org.odk.share.activities.WifiActivity.onStop(WifiActivity.java:183)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1210)
        at android.app.Activity.performStop(Activity.java:5158)
        at android.app.ActivityThread.handleSleeping(ActivityThread.java:3289)
        at android.app.ActivityThread.access$2700(ActivityThread.java:181)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:5042)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lognaturel** [comment]
At the very least, it should never be possible for the "Connecting to wifi" dialog to block the back button. It should be possible for a user to stop connecting and try again.

**Comment by lognaturel** [comment]
I also get in this state consistently when the One Touch is sending and the Galaxy Tab A is receiving.

**Comment by lakshyagupta21** [comment]
> Perhaps the state happens when trying to connect to a network that doesn't exist?

Maybe that's why it keeps on searching for the wifi connection and it doesn't stop.
