### ISSUE TITLE
Receiver not registered crash

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#65]
Alcatel OneTouch, Android 4.1.1. When receiving and not finding a network, after some time, Share crashes with:

```
07-19 21:48:28.886 13902-13902/org.odk.share E/WifiActivity: java.lang.IllegalArgumentException: Receiver not registered: org.odk.share.activities.WifiActivity$8@417e6710
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1214)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:378)
        at org.odk.share.activities.WifiActivity.onStop(WifiActivity.java:183)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1210)
        at android.app.Activity.performStop(Activity.java:5158)
        at android.app.ActivityThread.handleSleeping(ActivityThread.java:3289)
        at android.app.ActivityThread.access$2700(ActivityThread.java:181)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:5042)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lognaturel** [comment]
Just got this again canceling an ongoing connection attempt that was hanging:

```
    java.lang.IllegalArgumentException: Receiver not registered: org.odk.share.activities.WifiActivity$8@41cf7860
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1214)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:378)
        at org.odk.share.activities.WifiActivity$10.onClick(WifiActivity.java:491)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:169)
```

**Comment by jddeep** [comment]
@shobhitagarwal1612 I would like to work on this issue. Can I be assigned?

**Comment by lakshyagupta21** [comment]
@jddeep You're free to work on any issue if no one has shown interest on it or no one has else claimed it.
But make sure you claim issue first by `@opendatakit-bot claim`

**Comment by shobhitagarwal1612** [comment]
While working on #155 I think I might have fixed that unknowingly. Please check out that branch before taking this issue on

**Comment by MarkGhabbour** [comment]
@opendatakit-bot claim
